export const ICONS: Record<string, string> = {
  "clear-night": "night",
  "partlycloudy-night": "night-partly-cloudy",
  cloudy: "cloudy",
  fog: "fog",
  hail: "hail",
  lightning: "lightning",
  "lightning-rainy": "lightning-rainy",
  partlycloudy: "partly-cloudy",
  pouring: "pouring",
  rainy: "rainy",
  snowy: "snowy",
  "snowy-rainy": "snowy-rainy",
  sunny: "sunny",
  windy: "windy",
  "windy-variant": "windy-variant",
  exceptional: "alert-outline",
};
